server:
    port: 8081

spring:
    application:
        name: "social"

    security:
        oauth2:
            client:
                registration:
                    facebook:
                        client-id: "xxx"
                        client-secret: "xxx"
                    google:
                        client-id: "xxx"
                        client-secret: "xxx"